export const DTC_MAP: Record<string, string> = {
  P0001: "Fuel Volume Regulator Control Circuit / Open",
  P0002: "Fuel Volume Regulator Control Circuit Range / Performance",
  P0003: "Fuel Volume Regulator Control Circuit Low",
  P0004: "Fuel Volume Regulator Control Circuit High",
  P0005: "Fuel Shutoff Valve Control Circuit / Open",
  P0006: "Fuel Shutoff Valve Control Circuit Low",
  P0007: "Fuel Shutoff Valve Control Circuit High",
  P0008: "Engine Position System Performance(Bank1)",
  P0009: "Engine Position System Performance(Bank2)",
  P0010: "ACamshaft Position Actuator Circuit(Bank1)",
  P0011: "ACamshaft Position-Timing Over-Advancedor System Performance(Bank1)",
  P0012: "ACamshaft Position-Timing Over-Retarded(Bank1)",
  P0013: "BCamshaft Position-Actuator Circuit(Bank1)",
  P0014: "BCamshaft Position-Timing Over-Advancedor System Performance(Bank1)",
  P0015: "BCamshaft Position-Timing Over-Retarded(Bank1)",
  P0016: "Crankshaft Position Camshaft Position Correlation(Bank1 Sensor A)",
  P0017: "Crankshaft Position Camshaft Position Correlation(Bank1 Sensor B)",
  P0018: "Crankshaft Position Camshaft Position Correlation(Bank2 Sensor A)",
  P0019: "Crankshaft Position Camshaft Position Correlation(Bank2 Sensor B)",
  P0020: "ACamshaft Position Actuator Circuit(Bank2)",
  P0021: "ACamshaft Position-Timing Over-Advancedor System Performance(Bank2)",
  P0022: "ACamshaft Position-Timing Over-Retarded(Bank2)",
  P0023: "BCamshaft Position-Actuator Circuit(Bank2)",
  P0024: "BCamshaft Position-Timing Over-Advancedor System Performance(Bank2)",
  P0025: "BCamshaft Position-Timing Over-Retarded(Bank2)",
  P0026: "Intake Valve Control Solenoid Circuit Range / Performance (Bank1)",
  P0027: "Exhaust Valve Control Solenoid Circuit Range / Performance (Bank1)",
  P0028: "Intake Valve Control Solenoid Circuit Range / Performance (Bank2)",
  P0029: "Exhaust Valve Control Solenoid Circuit Range / Performance (Bank2)",
  P0030: "HO2SHeater Control Circuit(Bank1Sensor1)",
  P0031: "HO2SHeater Control Circuit Low(Bank1Sensor1)",
  P0032: "HO2SHeater Control Circuit High(Bank1Sensor1)",
  P0033: "Turbo Charger Bypass Valve Control Circuit",
  P0034: "Turbo Charger Bypass Valve Control Circuit Low",
  P0035: "Turbo Charger Bypass Valve Control Circuit High",
  P0036: "HO2SHeater Control Circuit(Bank1Sensor2)",
  P0037: "HO2SHeater Control Circuit Low(Bank1Sensor2)",
  P0038: "HO2SHeater Control Circuit High(Bank1Sensor2)",
  P0039:
    "Turbo / Super Charger Bypass Valve Control Circuit Range / Performance",
  P0040: "O2Sensor Signals Swapped Bank1Sensor1 / Bank2Sensor1",
  P0041: "O2Sensor Signals Swapped Bank1Sensor2 / Bank2Sensor2",
  P0042: "HO2SHeater Control Circuit(Bank1Sensor3)",
  P0043: "HO2SHeater Control Circuit Low(Bank1Sensor3)",
  P0044: "HO2SHeater Control Circuit High(Bank1Sensor3)",
  P0045: "Turbo / Super Charger Boost Control Solenoid Circuit / Open",
  P0046:
    "Turbo / Super Charger Boost Control Solenoid Circuit Range / Performance",
  P0047: "Turbo / Super Charger Boost Control Solenoid Circuit Low",
  P0048: "Turbo / Super Charger Boost Control Solenoid Circuit High",
  P0049: "Turbo / Super Charger Turbine Overspeed",
  P0050: "HO2SHeater Control Circuit(Bank2Sensor1)",
  P0051: "HO2SHeater Control Circuit Low(Bank2Sensor1)",
  P0052: "HO2SHeater Control Circuit High(Bank2Sensor1)",
  P0053: "HO2SHeater Resistance(Bank1Sensor1)",
  P0054: "HO2SHeater Resistance(Bank1Sensor2)",
  P0055: "HO2SHeater Resistance(Bank1Sensor3)",
  P0056: "HO2SHeater Control Circuit(Bank2Sensor2)",
  P0057: "HO2SHeater Control Circuit Low(Bank2Sensor2)",
  P0058: "HO2SHeater Control Circuit High(Bank2Sensor2)",
  P0059: "HO2SHeater Resistance(Bank2Sensor1)",
  P0060: "HO2SHeater Resistance(Bank2Sensor2)",
  P0061: "HO2SHeater Resistance(Bank2Sensor3)",
  P0062: "HO2SHeater Control Circuit(Bank2Sensor3)",
  P0063: "HO2SHeater Control Circuit Low(Bank2Sensor3)",
  P0064: "HO2SHeater Control Circuit High(Bank2Sensor3)",
  P0065: "Air Assisted Injector Control Range / Performance",
  P0066: "Air Assisted Injector Control Circuitor Circuit Low",
  P0067: "Air Assisted Injector Control Circuit High",
  P0068: "MAP / MAFThrottle Position Correlation",
  P0069: "Manifold Absolute Pressure Barometric Pressure Correlation",
  P0070: "Ambient Air Temperature Sensor Circuit",
  P0071: "Ambient Air Temperature Sensor Range / Performance",
  P0072: "Ambient Air Temperature Sensor Circuit Low",
  P0073: "Ambient Air Temperature Sensor Circuit High",
  P0074: "Ambient Air Temperature Sensor Circuit Intermittent",
  P0075: "Intake Valve Control Solenoid Circuit(Bank1)",
  P0076: "Intake Valve Control Solenoid Circuit Low(Bank1)",
  P0077: "Intake Valve Control Solenoid Circuit High(Bank1)",
  P0078: "Exhaust Valve Control Solenoid Circuit(Bank1)",
  P0079: "Exhaust Valve Control Solenoid Circuit Low(Bank1)",
  P0080: "Exhaust Valve Control Solenoid Circuit High(Bank1)",
  P0081: "Intake Valve Control Solenoid Circuit(Bank2)",
  P0082: "Intake Valve Control Solenoid Circuit Low(Bank2)",
  P0083: "Intake Valve Control Solenoid Circuit High(Bank2)",
  P0084: "Exhaust Valve Control Solenoid Circuit(Bank2)",
  P0085: "Exhaust Valve Control Solenoid Circuit Low(Bank2)",
  P0086: "Exhaust Valve Control Solenoid Circuit High(Bank2)",
  P0087: "Fuel Rail / System Pressure-Too Low",
  P0088: "Fuel Rail / System Pressure-Too High",
  P0089: "Fuel Pressure Regulator1Performance",
  P0090: "Fuel Pressure Regulator1Control Circuit",
  P0091: "Fuel Pressure Regulator1Control Circuit Low",
  P0092: "Fuel Pressure Regulator1Control Circuit High",
  P0093: "Fuel System Leak Detected Large Leak",
  P0094: "Fuel System Leak Detected Small Leak",
  P0095: "Intake Air Temperature Sensor2Circuit",
  P0096: "Intake Air Temperature Sensor2Circuit Range / Performance",
  P0097: "Intake Air Temperature Sensor2Circuit Low",
  P0098: "Intake Air Temperature Sensor2Circuit High",
  P0099: "Intake Air Temperature Sensor2Circuit Intermittent / Erratic",
  P0100: "Massor Volume Air Flow Circuit Malfunction",
  P0101: "Massor Volume Air Flow Circuit Range / Performance Problem",
  P0102: "Massor Volume Air Flow Circuit Low Input",
  P0103: "Massor Volume Air Flow Circuit High Input",
  P0104: "Massor Volume Air Flow Circuit Intermittent",
  P0105: "Manifold Absolute Pressure / Barometric Pressure Circuit Malfunction",
  P0106:
    "Manifold Absolute Pressure / Barometric Pressure Circuit Range / Performance Problem",
  P0107: "Manifold Absolute Pressure / Barometric Pressure Circuit Low Input",
  P0108: "Manifold Absolute Pressure / Barometric Pressure Circuit High Input",
  P0109:
    "Manifold Absolute Pressure / Barometric Pressure Circuit Intermittent",
  P0110: "Intake Air Temperature Circuit Malfunction",
  P0111: "Intake Air Temperature Circuit Range / Performance Problem",
  P0112: "Intake Air Temperature Circuit Low Input",
  P0113: "Intake Air Temperature Circuit High Input",
  P0114: "Intake Air Temperature Circuit Intermittent",
  P0115: "Engine Coolant Temperature Circuit Malfunction",
  P0116: "Engine Coolant Temperature Circuit Range / Performance Problem",
  P0117: "Engine Coolant Temperature Circuit Low Input",
  P0118: "Engine Coolant Temperature Circuit High Input",
  P0119: "Engine Coolant Temperature Circuit Intermittent",
  P0120: "Throttle Position Sensor / Switch ACircuit Malfunction",
  P0121:
    "Throttle Position Sensor / Switch ACircuit Range / Performance Problem",
  P0122: "Throttle Position Sensor / Switch ACircuit Low Input",
  P0123: "Throttle Position Sensor / Switch ACircuit High Input",
  P0124: "Throttle Position Sensor / Switch ACircuit Intermittent",
  P0125:
    "Insufficient Coolant Temperaturefor Closed Loop Fuel Control; ECTExcessive Timeto Closed Loop Fuel Control",
  P0126: "Insufficient Coolant Temperaturefor Stable Operation",
  P0128: "Coolant Thermostat Malfunction",
  P0129: "Barometric Pressure Too Low",
  P0130: "O2Sensor Circuit Malfunction(Bank1Sensor1)",
  P0131: "O2Sensor Circuit Low Voltage(Bank1Sensor1)",
  P0132: "O2Sensor Circuit High Voltage(Bank1Sensor1)",
  P0133: "O2Sensor Circuit Slow Response(Bank1Sensor1)",
  P0134: "O2Sensor Circuit No Activity Detected(Bank1Sensor1)",
  P0135: "O2Sensor Heater Circuit Malfunction(Bank1Sensor1)",
  P0136: "O2Sensor Circuit Malfunction(Bank1Sensor2)",
  P0137: "O2Sensor Circuit Low Voltage(Bank1Sensor2)",
  P0138: "O2Sensor Circuit High Voltage(Bank1Sensor2)",
  P0139: "O2Sensor Circuit Slow Response(Bank1Sensor2)",
  P0140: "O2Sensor Circuit No Activity Detected(Bank1Sensor2)",
  P0141: "O2Sensor Heater Circuit Malfunction(Bank1Sensor2)",
  P0142: "O2Sensor Circuit Malfunction(Bank1Sensor3)",
  P0143: "O2Sensor Circuit Low Voltage(Bank1Sensor3)",
  P0144: "O2Sensor Circuit High Voltage(Bank1Sensor3)",
  P0145: "O2Sensor Circuit Slow Response(Bank1Sensor3)",
  P0146: "O2Sensor Circuit No Activity Detected(Bank1Sensor3)",
  P0147: "O2Sensor Heater Circuit Malfunction(Bank1Sensor3)",
  P0150: "O2Sensor Circuit Malfunction(Bank2Sensor1)",
  P0151: "O2Sensor Circuit Low Voltage(Bank2Sensor1)",
  P0152: "O2Sensor Circuit High Voltage(Bank2Sensor1)",
  P0153: "O2Sensor Circuit Slow Response(Bank2Sensor1)",
  P0154: "O2Sensor Circuit No Activity Detected(Bank2Sensor1)",
  P0155: "O2Sensor Heater Circuit Malfunction(Bank2Sensor1)",
  P0156: "O2Sensor Circuit Malfunction(Bank2Sensor2)",
  P0157: "O2Sensor Circuit Low Voltage(Bank2Sensor2)",
  P0158: "O2Sensor Circuit High Voltage(Bank2Sensor2)",
  P0159: "O2Sensor Circuit Slow Response(Bank2Sensor2)",
  P0160: "O2Sensor Circuit No Activity Detected(Bank2Sensor2)",
  P0161: "O2Sensor Heater Circuit Malfunction(Bank2Sensor2)",
  P0162: "O2Sensor Circuit Malfunction(Bank2Sensor3)",
  P0163: "O2Sensor Circuit Low Voltage(Bank2Sensor3)",
  P0164: "O2Sensor Circuit High Voltage(Bank2Sensor3)",
  P0165: "O2Sensor Circuit Slow Response(Bank2Sensor3)",
  P0166: "O2Sensor Circuit No Activity Detected(Bank2Sensor3)",
  P0167: "O2Sensor Heater Circuit Malfunction(Bank2Sensor3)",
  P0170: "Fuel Trim Malfunction(Bank1)",
  P0171: "Fuel Trimtoo Lean(Bank1)",
  P0172: "Fuel Trimtoo Rich(Bank1)",
  P0173: "Fuel Trim Malfunction(Bank2)",
  P0174: "Fuel Trimtoo Lean(Bank2)",
  P0175: "Fuel Trimtoo Rich(Bank2)",
  P0176: "Fuel Composition Sensor Circuit Malfunction",
  P0177: "Fuel Composition Sensor Circuit Range / Performance",
  P0178: "Fuel Composition Sensor Circuit Low Input",
  P0179: "Fuel Composition Sensor Circuit High Input",
  P0180: "Fuel Temperature Sensor ACircuit Malfunction",
  P0181: "Fuel Temperature Sensor ACircuit Range / Performance",
  P0182: "Fuel Temperature Sensor ACircuit Low Input",
  P0183: "Fuel Temperature Sensor ACircuit High Input",
  P0184: "Fuel Temperature Sensor ACircuit Intermittent",
  P0185: "Fuel Temperature Sensor BCircuit Malfunction",
  P0186: "Fuel Temperature Sensor BCircuit Range / Performance",
  P0187: "Fuel Temperature Sensor BCircuit Low Input",
  P0188: "Fuel Temperature Sensor BCircuit High Input",
  P0189: "Fuel Temperature Sensor BCircuit Intermittent",
  P0190: "Fuel Rail Pressure Sensor Circuit Malfunction",
  P0191: "Fuel Rail Pressure Sensor Circuit Range / Performance",
  P0192: "Fuel Rail Pressure Sensor Circuit Low Input",
  P0193: "Fuel Rail Pressure Sensor Circuit High Input",
  P0194: "Fuel Rail Pressure Sensor Circuit Intermittent",
  P0195: "Engine Oil Temperature Sensor Malfunction",
  P0196: "Engine Oil Temperature Sensor Range / Performance",
  P0197: "Engine Oil Temperature Sensor Low",
  P0198: "Engine Oil Temperature Sensor High",
  P0199: "Engine Oil Temperature Sensor Intermittent",
  P0200: "Injector Circuit Malfunction",
  P0201: "Injector Circuit Malfunction-Cylinder1",
  P0202: "Injector Circuit Malfunction-Cylinder2",
  P0203: "Injector Circuit Malfunction-Cylinder3",
  P0204: "Injector Circuit Malfunction-Cylinder4",
  P0205: "Injector Circuit Malfunction-Cylinder5",
  P0206: "Injector Circuit Malfunction-Cylinder6",
  P0207: "Injector Circuit Malfunction-Cylinder7",
  P0208: "Injector Circuit Malfunction-Cylinder8",
  P0209: "Injector Circuit Malfunction-Cylinder9",
  P0210: "Injector Circuit Malfunction-Cylinder10",
  P0211: "Injector Circuit Malfunction-Cylinder11",
  P0212: "Injector Circuit Malfunction-Cylinder12",
  P0213: "Cold Start Injector1Malfunction",
  P0214: "Cold Start Injector2Malfunction",
  P0215: "Engine Shutoff Solenoid Malfunction",
  P0216: "Injection Timing Control Circuit Malfunction",
  P0217: "Engine Overtemp Condition",
  P0218: "Transmission Over Temperature Condition",
  P0219: "Engine Overspeed Condition",
  P0220: "Throttle / Petal Position Sensor / Switch BCircuit Malfunction",
  P0221:
    "Throttle / Petal Position Sensor / Switch BCircuit Range / Performance Problem",
  P0222: "Throttle / Petal Position Sensor / Switch BCircuit Low Input",
  P0223: "Throttle / Petal Position Sensor / Switch BCircuit High Input",
  P0224: "Throttle / Petal Position Sensor / Switch BCircuit Intermittent",
  P0225: "Throttle / Petal Position Sensor / Switch CCircuit Malfunction",
  P0226:
    "Throttle / Petal Position Sensor / Switch CCircuit Range / Performance Problem",
  P0227: "Throttle / Petal Position Sensor / Switch CCircuit Low Input",
  P0228: "Throttle / Petal Position Sensor / Switch CCircuit High Input",
  P0229: "Throttle / Petal Position Sensor / Switch CCircuit Intermittent",
  P0230: "Fuel Pump Primary Circuit Malfunction",
  P0231: "Fuel Pump Secondary Circuit Low",
  P0232: "Fuel Pump Secondary Circuit High",
  P0233: "Fuel Pump Secondary Circuit Intermittent",
  P0234: "Engine Overboost Condition",
  P0235: "Turbocharger Boost Sensor ACircuit Malfunction",
  P0236: "Turbocharger Boost Sensor ACircuit Range / Performance",
  P0237: "Turbocharger Boost Sensor ACircuit Low",
  P0238: "Turbocharger Boost Sensor ACircuit High",
  P0239: "Turbocharger Boost Sensor BMalfunction",
  P0240: "Turbocharger Boost Sensor BCircuit Range / Performance",
  P0241: "Turbocharger Boost Sensor BCircuit Low",
  P0242: "Turbocharger Boost Sensor BCircuit High",
  P0243: "Turbocharger Wastegate Solenoid AMalfunction",
  P0244: "Turbocharger Wastegate Solenoid ARange / Performance",
  P0245: "Turbocharger Wastegate Solenoid ALow",
  P0246: "Turbocharger Wastegate Solenoid AHigh",
  P0247: "Turbocharger Wastegate Solenoid BMalfunction",
  P0248: "Turbocharger Wastegate Solenoid BRange / Performance",
  P0249: "Turbocharger Wastegate Solenoid BLow",
  P0250: "Turbocharger Wastegate Solenoid BHigh",
  P0251:
    'Injection Pump Fuel Metering Control"A"Malfunction (Cam / Rotor / Injector)',
  P0252:
    'Injection Pump Fuel Metering Control"A"Range / Performance (Cam / Rotor / Injector)',
  P0253: 'Injection Pump Fuel Metering Control"A"Low (Cam / Rotor / Injector)',
  P0254: 'Injection Pump Fuel Metering Control"A"High (Cam / Rotor / Injector)',
  P0255:
    'Injection Pump Fuel Metering Control"A"Intermittent (Cam / Rotor / Injector)',
  P0256:
    'Injection Pump Fuel Metering Control"B"Malfunction (Cam / Rotor / Injector)',
  P0257:
    'Injection Pump Fuel Metering Control"B"Range / Performance (Cam / Rotor / Injector)',
  P0258: 'Injection Pump Fuel Metering Control"B"Low (Cam / Rotor / Injector)',
  P0259: 'Injection Pump Fuel Metering Control"B"High (Cam / Rotor / Injector)',
  P0260:
    'Injection Pump Fuel Metering Control"B"Intermittent (Cam / Rotor / Injector)',
  P0261: "Cylinder1Injector Circuit Low",
  P0262: "Cylinder1Injector Circuit High",
  P0263: "Cylinder1Contribution / Balance Fault",
  P0264: "Cylinder2Injector Circuit Low",
  P0265: "Cylinder2Injector Circuit High",
  P0266: "Cylinder2Contribution / Balance Fault",
  P0267: "Cylinder3Injector Circuit Low",
  P0268: "Cylinder3Injector Circuit High",
  P0269: "Cylinder3Contribution / Balance Fault",
  P0270: "Cylinder4Injector Circuit Low",
  P0271: "Cylinder4Injector Circuit High",
  P0272: "Cylinder4Contribution / Balance Fault",
  P0273: "Cylinder5Injector Circuit Low",
  P0274: "Cylinder5Injector Circuit High",
  P0275: "Cylinder5Contribution / Balance Fault",
  P0276: "Cylinder6Injector Circuit Low",
  P0277: "Cylinder6Injector Circuit High",
  P0278: "Cylinder6Contribution / Balance Fault",
  P0279: "Cylinder7Injector Circuit Low",
  P0280: "Cylinder7Injector Circuit High",
  P0281: "Cylinder7Contribution / Balance Fault",
  P0282: "Cylinder8Injector Circuit Low",
  P0283: "Cylinder8Injector Circuit High",
  P0284: "Cylinder8Contribution / Balance Fault",
  P0285: "Cylinder9Injector Circuit Low",
  P0286: "Cylinder9Injector Circuit High",
  P0287: "Cylinder9Contribution / Balance Fault",
  P0288: "Cylinder10Injector Circuit Low",
  P0289: "Cylinder10Injector Circuit High",
  P0290: "Cylinder10Contribution / Balance Fault",
  P0291: "Cylinder11Injector Circuit Low",
  P0292: "Cylinder11Injector Circuit High",
  P0293: "Cylinder11Contribution / Balance Fault",
  P0294: "Cylinder12Injector Circuit Low",
  P0295: "Cylinder12Injector Circuit High",
  P0296: "Cylinder12Contribution / Range Fault",
  P0300: "Random / Multiple Cylinder Misfire Detected",
  P0301: "Cylinder1Misfire Detected",
  P0302: "Cylinder2Misfire Detected",
  P0303: "Cylinder3Misfire Detected",
  P0304: "Cylinder4Misfire Detected",
  P0305: "Cylinder5Misfire Detected",
  P0306: "Cylinder6Misfire Detected",
  P0307: "Cylinder7Misfire Detected",
  P0308: "Cylinder8Misfire Detected",
  P0309: "Cylinder9Misfire Detected",
  P0310: "Cylinder10Misfire Detected",
  P0311: "Cylinder11Misfire Detected",
  P0312: "Cylinder12Misfire Detected",
  P0320: "Ignition / Distributor Engine Speed Input Circuit Malfunction",
  P0321:
    "Ignition / Distributor Engine Speed Input Circuit Range / Performance",
  P0322: "Ignition / Distributor Engine Speed Input Circuit No Signal",
  P0323: "Ignition / Distributor Engine Speed Input Circuit Intermittent",
  P0325: "Knock Sensor1Circuit Malfunction(Bank1or Single Sensor)",
  P0326: "Knock Sensor1Circuit Range / Performance(Bank1or Single Sensor)",
  P0327: "Knock Sensor1Circuit Low Input(Bank1or Single Sensor)",
  P0328: "Knock Sensor1Circuit High Input(Bank1or Single Sensor)",
  P0329: "Knock Sensor1Circuit Intermittent(Bank1or Single Sensor)",
  P0330: "Knock Sensor2Circuit Malfunction(Bank2)",
  P0331: "Knock Sensor2Circuit Range / Performance(Bank2)",
  P0332: "Knock Sensor2Circuit Low Input(Bank2)",
  P0333: "Knock Sensor2Circuit High Input(Bank2)",
  P0334: "Knock Sensor2Circuit Intermittent(Bank2)",
  P0335: "Crankshaft Position Sensor ACircuit Malfunction",
  P0336: "Crankshaft Position Sensor ACircuit Range / Performance",
  P0337: "Crankshaft Position Sensor ACircuit Low Input",
  P0338: "Crankshaft Position Sensor ACircuit High Input",
  P0339: "Crankshaft Position Sensor ACircuit Intermittent",
  P0340: "Camshaft Position Sensor Circuit Malfunction",
  P0341: "Camshaft Position Sensor Circuit Range / Performance",
  P0342: "Camshaft Position Sensor Circuit Low Input",
  P0343: "Camshaft Position Sensor Circuit High Input",
  P0344: "Camshaft Position Sensor Circuit Intermittent",
  P0350: "Ignition Coil Primary / Secondary Circuit Malfunction",
  P0351: "Ignition Coil APrimary / Secondary Circuit Malfunction",
  P0352: "Ignition Coil BPrimary / Secondary Circuit Malfunction",
  P0353: "Ignition Coil CPrimary / Secondary Circuit Malfunction",
  P0354: "Ignition Coil DPrimary / Secondary Circuit Malfunction",
  P0355: "Ignition Coil EPrimary / Secondary Circuit Malfunction",
  P0356: "Ignition Coil FPrimary / Secondary Circuit Malfunction",
  P0357: "Ignition Coil GPrimary / Secondary Circuit Malfunction",
  P0358: "Ignition Coil HPrimary / Secondary Circuit Malfunction",
  P0359: "Ignition Coil IPrimary / Secondary Circuit Malfunction",
  P0360: "Ignition Coil JPrimary / Secondary Circuit Malfunction",
  P0361: "Ignition Coil KPrimary / Secondary Circuit Malfunction",
  P0362: "Ignition Coil LPrimary / Secondary Circuit Malfunction",
  P0370: "Timing Reference High Resolution Signal AMalfunction",
  P0371: "Timing Reference High Resolution Signal AToo Many Pulses",
  P0372: "Timing Reference High Resolution Signal AToo Few Pulses",
  P0373:
    "Timing Reference High Resolution Signal AIntermittent / Erratic Pulses",
  P0374: "Timing Reference High Resolution Signal ANo Pulses",
  P0375: "Timing Reference High Resolution Signal BMalfunction",
  P0376: "Timing Reference High Resolution Signal BToo Many Pulses",
  P0377: "Timing Reference High Resolution Signal BToo Few Pulses",
  P0378:
    "Timing Reference High Resolution Signal BIntermittent / Erratic Pulses",
  P0379: "Timing Reference High Resolution Signal BNo Pulses",
  P0380: 'Glow Plug / Heater Circuit"A"Malfunction',
  P0381: "Glow Plug / Heater Indicator Circuit Malfunction",
  P0382: "Exhaust Gas Recirculation Flow Malfunction",
  P0385: "Crankshaft Position Sensor BCircuit Malfunction",
  P0386: "Crankshaft Position Sensor BCircuit Range / Performance",
  P0387: "Crankshaft Position Sensor BCircuit Low Input",
  P0388: "Crankshaft Position Sensor BCircuit High Input",
  P0389: "Crankshaft Position Sensor BCircuit Intermittent",
  P0400: "Exhaust Gas Recirculation Flow Malfunction",
  P0401: "Exhaust Gas Recirculation Flow Insufficient Detected",
  P0402: "Exhaust Gas Recirculation Flow Excessive Detected",
  P0403: "Exhaust Gas Recirculation Circuit Malfunction",
  P0404: "Exhaust Gas Recirculation Circuit Range / Performance",
  P0405: "Exhaust Gas Recirculation Sensor ACircuit Low",
  P0406: "Exhaust Gas Recirculation Sensor ACircuit High",
  P0407: "Exhaust Gas Recirculation Sensor BCircuit Low",
  P0408: "Exhaust Gas Recirculation Sensor BCircuit High",
  P0410: "Secondary Air Injection System Malfunction",
  P0411: "Secondary Air Injection System Incorrect Flow Detected",
  P0412: "Secondary Air Injection System Switching Valve ACircuit Malfunction",
  P0413: "Secondary Air Injection System Switching Valve ACircuit Open",
  P0414: "Secondary Air Injection System Switching Valve ACircuit Shorted",
  P0415: "Secondary Air Injection System Switching Valve BCircuit Malfunction",
  P0416: "Secondary Air Injection System Switching Valve BCircuit Open",
  P0417: "Secondary Air Injection System Switching Valve BCircuit Shorted",
  P0418: 'Secondary Air Injection System Relay"A"Circuit Malfunction',
  P0419: 'Secondary Air Injection System Relay"B"Circuit Malfunction',
  P0420: "Catalyst System Efficiency Below Threshold(Bank1)",
  P0421: "Warm Up Catalyst Efficiency Below Threshold(Bank1)",
  P0422: "Main Catalyst Efficiency Below Threshold(Bank1)",
  P0423: "Heated Catalyst Efficiency Below Threshold(Bank1)",
  P0424: "Heated Catalyst Temperature Below Threshold(Bank1)",
  P0426: "Catalyst Temperature Sensor Range / Performance(Bank1)",
  P0427: "Catalyst Temperature Sensor Low Input(Bank1)",
  P0428: "Catalyst Temperature Sensor High Input(Bank1)",
  P0430: "Catalyst System Efficiency Below Threshold(Bank2)",
  P0431: "Warm Up Catalyst Efficiency Below Threshold(Bank2)",
  P0432: "Main Catalyst Efficiency Below Threshold(Bank2)",
  P0433: "Heated Catalyst Efficiency Below Threshold(Bank2)",
  P0434: "Heated Catalyst Temperature Below Threshold(Bank2)",
  P0436: "Catalyst Temperature Sensor Range / Performance(Bank2)",
  P0437: "Catalyst Temperature Sensor Low Input(Bank2)",
  P0438: "Catalyst Temperature Sensor High Input(Bank2)",
  P0440: "Evaporative Emission Control System Malfunction",
  P0441: "Evaporative Emission Control System Incorrect Purge Flow",
  P0442: "Evaporative Emission Control System Leak Detected(small leak)",
  P0443:
    "Evaporative Emission Control System Purge Control Valve Circuit Malfunction",
  P0444: "Evaporative Emission Control System Purge Control Valve Circuit Open",
  P0445:
    "Evaporative Emission Control System Purge Control Valve Circuit Shorted",
  P0446: "Evaporative Emission Control System Vent Control Circuit Malfunction",
  P0447: "Evaporative Emission Control System Vent Control Circuit Open",
  P0448: "Evaporative Emission Control System Vent Control Circuit Shorted",
  P0449:
    "Evaporative Emission Control System Vent Valve / Solenoid Circuit Malfunction",
  P0450: "Evaporative Emission Control System Pressure Sensor Malfunction",
  P0451:
    "Evaporative Emission Control System Pressure Sensor Range / Performance",
  P0452: "Evaporative Emission Control System Pressure Sensor Low Input",
  P0453: "Evaporative Emission Control System Pressure Sensor High Input",
  P0454: "Evaporative Emission Control System Pressure Sensor Intermittent",
  P0455: "Evaporative Emission Control System Leak Detected(gross leak)",
  P0460: "Fuel Level Sensor Circuit Malfunction",
  P0461: "Fuel Level Sensor Circuit Range / Performance",
  P0462: "Fuel Level Sensor Circuit Low Input",
  P0463: "Fuel Level Sensor Circuit High Input",
  P0464: "Fuel Level Sensor Circuit Intermittent",
  P0465: "Purge Flow Sensor Circuit Malfunction",
  P0466: "Purge Flow Sensor Circuit Range / Performance",
  P0467: "Purge Flow Sensor Circuit Low Input",
  P0468: "Purge Flow Sensor Circuit High Input",
  P0469: "Purge Flow Sensor Circuit Intermittent",
  P0470: "Exhaust Pressure Sensor Malfunction",
  P0471: "Exhaust Pressure Sensor Range / Performance",
  P0472: "Exhaust Pressure Sensor Low",
  P0473: "Exhaust Pressure Sensor High",
  P0474: "Exhaust Pressure Sensor Intermittent",
  P0475: "Exhaust Pressure Control Valve Malfunction",
  P0476: "Exhaust Pressure Control Valve Range / Performance",
  P0477: "Exhaust Pressure Control Valve Low",
  P0478: "Exhaust Pressure Control Valve High",
  P0479: "Exhaust Pressure Control Valve Intermittent",
  P0480: "Cooling Fan1Control Circuit Malfunction",
  P0481: "Cooling Fan2Control Circuit Malfunction",
  P0482: "Cooling Fan3Control Circuit Malfunction",
  P0483: "Cooling Fan Rationality Check Malfunction",
  P0484: "Cooling Fan Circuit Over Current",
  P0485: "Cooling Fan Power / Ground Circuit Malfunction",
  P0500: "Vehicle Speed Sensor Malfunction",
  P0501: "Vehicle Speed Sensor Range / Performance",
  P0502: "Vehicle Speed Sensor Low Input",
  P0503: "Vehicle Speed Sensor Intermittent / Erratic / High",
  P0505: "Idle Control System Malfunction",
  P0506: "Idle Control System RPMLower Than Expected",
  P0507: "Idle Control System RPMHigher Than Expected",
  P0510: "Closed Throttle Position Switch Malfunction",
  P0520: "Engine Oil Pressure Sensor / Switch Circuit Malfunction",
  P0521: "Engine Oil Pressure Sensor / Switch Circuit Range / Performance",
  P0522: "Engine Oil Pressure Sensor / Switch Circuit Low Voltage",
  P0523: "Engine Oil Pressure Sensor / Switch Circuit High Voltage",
  P0530: "A / CRefrigerant Pressure Sensor Circuit Malfunction",
  P0531: "A / CRefrigerant Pressure Sensor Circuit Range / Performance",
  P0532: "A / CRefrigerant Pressure Sensor Circuit Low Input",
  P0533: "A / CRefrigerant Pressure Sensor Circuit High Input",
  P0534: "Air Conditioner Refrigerant Charge Loss",
  P0550: "Power Steering Pressure Sensor Circuit Malfunction",
  P0551: "Power Steering Pressure Sensor Circuit Range / Performance",
  P0552: "Power Steering Pressure Sensor Circuit Low Input",
  P0553: "Power Steering Pressure Sensor Circuit High Input",
  P0554: "Power Steering Pressure Sensor Circuit Intermittent",
  P0560: "System Voltage Malfunction",
  P0561: "System Voltage Unstable",
  P0562: "System Voltage Low",
  P0563: "System Voltage High",
  P0565: "Cruise Control On Signal Malfunction",
  P0566: "Cruise Control Off Signal Malfunction",
  P0567: "Cruise Control Resume Signal Malfunction",
  P0568: "Cruise Control Set Signal Malfunction",
  P0569: "Cruise Control Coast Signal Malfunction",
  P0570: "Cruise Control Accel Signal Malfunction",
  P0571: "Cruise Control / Brake Switch ACircuit Malfunction",
  P0572: "Cruise Control / Brake Switch ACircuit Low",
  P0573: "Cruise Control / Brake Switch ACircuit High",
  P0574: "Cruise Control Related Malfunction",
  P0575: "Cruise Control Related Malfunction",
  P0576: "Cruise Control Related Malfunction",
  P0578: "Cruise Control Related Malfunction",
  P0579: "Cruise Control Related Malfunction",
  P0580: "Cruise Control Related Malfunction",
  P0600: "Serial Communication Link Malfunction",
  P0601: "Control Module Read Only Memory(ROM)",
  P0602: "Control Module Programming Error",
  P0603: "Internal Control Module Keep Alive Memory(KAM)Error",
  P0604: "Internal Control Module Random Access Memory(RAM)Error",
  P0605: "Internal Control Module Read Only Memory(ROM)Error",
  P0606: "PCMProcessor Fault",
  P0608: 'Control Module VSSOutput"A"Malfunction',
  P0609: 'Control Module VSSOutput"B"Malfunction',
  P0620: "Generator Control Circuit Malfunction",
  P0621: 'Generator Lamp"L"Control Circuit Malfunction',
  P0622: 'Generator Field"F"Control Circuit Malfunction',
  P0650: "Malfunction Indicator Lamp(MIL)Control Circuit Malfunction",
  P0654: "Engine RPMOutput Circuit Malfunction",
  P0655: "Engine Hot Lamp Output Control Circuit Malfucntion",
  P0656: "Fuel Level Output Circuit Malfunction",
  P0700: "Transmission Control System Malfunction",
  P0701: "Transmission Control System Range / Performance",
  P0702: "Transmission Control System Electrical",
  P0703: "Torque Converter / Brake Switch BCircuit Malfunction",
  P0704: "Clutch Switch Input Circuit Malfunction",
  P0705: "Transmission Range Sensor Circuitmalfunction(PRNDLInput)",
  P0706: "Transmission Range Sensor Circuit Range / Performance",
  P0707: "Transmission Range Sensor Circuit Low Input",
  P0708: "Transmission Range Sensor Circuit High Input",
  P0709: "Transmission Range Sensor Circuit Intermittent",
  P0710: "Transmission Fluid Temperature Sensor Circuit Malfunction",
  P0711: "Transmission Fluid Temperature Sensor Circuit Range / Performance",
  P0712: "Transmission Fluid Temperature Sensor Circuit Low Input",
  P0713: "Transmission Fluid Temperature Sensor Circuit High Input",
  P0714: "Transmission Fluid Temperature Sensor Circuit Intermittent",
  P0715: "Input / Turbine Speed Sensor Circuit Malfunction",
  P0716: "Input / Turbine Speed Sensor Circuit Range / Performance",
  P0717: "Input / Turbine Speed Sensor Circuit No Signal",
  P0718: "Input / Turbine Speed Sensor Circuit Intermittent",
  P0719: "Torque Converter / Brake Switch BCircuit Low",
  P0720: "Output Speed Sensor Circuit Malfunction",
  P0721: "Output Speed Sensor Range / Performance",
  P0722: "Output Speed Sensor No Signal",
  P0723: "Output Speed Sensor Intermittent",
  P0724: "Torque Converter / Brake Switch BCircuit High",
  P0725: "Engine Speedinput Circuit Malfunction",
  P0726: "Engine Speed Input Circuit Range / Performance",
  P0727: "Engine Speed Input Circuit No Signal",
  P0728: "Engine Speed Input Circuit Intermittent",
  P0730: "Incorrect Gear Ratio",
  P0731: "Gear1Incorrectratio",
  P0732: "Gear2Incorrectratio",
  P0733: "Gear3Incorrectratio",
  P0734: "Gear4Incorrectratio",
  P0735: "Gear5Incorrectratio",
  P0736: "Reverseincorrectgearratio",
  P0740: "Torque Converter Clutch Circuit Malfuction",
  P0741: "Torque Converter Clutch Circuit Performanceor Stuck Off",
  P0742: "Torque Converter Clutch Circuit Stuck On",
  P0743: "Torque Converter Clutch Circuit Electrical",
  P0744: "Torque Converter Clutch Circuit Intermittent",
  P0745: "Pressure Control Solenoid Malfunction",
  P0746: "Pressure Control Solenoid Performanceor Stuck Off",
  P0747: "Pressure Control Solenoid Stuck On",
  P0748: "Pressure Control Solenoid Electrical",
  P0749: "Pressure Control Solenoid Intermittent",
  P0750: "Shift Solenoid AMalfunction",
  P0751:
    "Shift Solenoid APerformanceor Stuck Off / 1-2Shift Solenoid Valve Performance",
  P0752: "Shift Solenoid AStuck On",
  P0753: "Shift Solenoid AElectrical / 1-2Shift Solenoid Circuit Electrical",
  P0754: "Shift Solenoid AIntermittent",
  P0755: "Shift Solenoid BMalfunction",
  P0756:
    "Shift Solenoid BPerformanceor Stuck Off / 2-3Shift Solenoid Valve Performance",
  P0757: "Shift Solenoid BStuck On",
  P0758: "Shift Solenoid BElectrical / 2-3Shift Solenoid Circuit Electrical",
  P0759: "Shift Solenoid BIntermittent",
  P0760: "Shift Solenoid CMalfunction",
  P0761: "Shift Solenoid CPerformanceor Stuck Off",
  P0762: "Shift Solenoid CStuck On",
  P0763: "Shift Solenoid CElectrical",
  P0764: "Shift Solenoid CIntermittent",
  P0765: "Shift Solenoid DMalfunction",
  P0766: "Shift Solenoid DPerformanceor Stuck Off",
  P0767: "Shift Solenoid DStuck On",
  P0768: "Shift Solenoid DElectrical",
  P0769: "Shift Solenoid DIntermittent",
  P0770: "Shift Solenoid EMalfunction",
  P0771: "Shift Solenoid EPerformanceor Stuck Off",
  P0772: "Shift Solenoid EStuck On",
  P0773: "Shift Solenoid EElectrical",
  P0774: "Shift Solenoid EIntermittent",
  P0775: "Pressure Control Solenoid BMalfunction",
  P0776: "Pressure Control Solenoid BPerformance",
  P0777: "Pressure Control Solenoid BStuck On",
  P0778: "Pressure Control Solenoid BElectrical",
  P0779: "Pressure Control Solenoid BIntermittent",
  P0780: "Shift Malfunction",
  P0781: "1-2Shift Malfunction",
  P0782: "2-3Shift Malfunction",
  P0783: "3-4Shift Malfunction",
  P0784: "4-5Shift Malfunction",
  P0785:
    "Shift / Timing Solenoid Malfunction / 3-2Shift Solenoid Circuit Electrical",
  P0786: "Shift / Timing Solenoid Range / Performance",
  P0787: "Shift / Timing Solenoid Low",
  P0788: "Shift / Timing Solenoid High",
  P0789: "Shift / Timing Solenoid Intermittent",
  P0790: "Normal / Performance Switch Circuit Malfunction",
  P0801: "Reverse Inhibit Control Circuit Malfunction",
  P0803: "1-4Upshift(Skip Shift)Solenoid Control Circuit Malfunction",
  P0804: "1-4Upshift(Skip Shift)Lamp Control Circuit Malfunction",
  P1100: "MAFSensor Intermittent / Checkofall OBDIISystems Not Complete",
  P1101:
    "MAFSensor Out Of Self Test Range. / KOERNot Able To Complete KOERAborted",
  P1102: "MAFSensor In Range But Lower Than Expected",
  P1103: "MAFSensor In Range But Higher Than Expected",
  P1104: "MAFGround Malfunction",
  P1105: "Dual Alternator Upper Fault",
  P1106:
    "Dual Alternator Lower Fault / Manifold Absolute Pressure(MAP) Sensor Circuit Intermittent High Voltage",
  P1107:
    "Dual Alternator Lower Circuit Malfunction / Manifold Absolute Pressure(MAP)Sensor Circuit Intermittent Low Voltage",
  P1108: "Dual Alternator Battery Lamp Circuit Malfunction",
  P1109: "IAT-BSensor Intermittent",
  P1110: "IATSensor(D / C)Open / Short",
  P1111: "Intake Air Temperature(IAT)Sensor Circuit Intermittent High Voltage",
  P1112: "Intake Air Temperature(IAT)Sensor Circuit Intermittent Low Voltage",
  P1113: "IATSensor Open / Short",
  P1114:
    "Engine Coolant Temperature(ECT)Sensor Circuit Intermittent Low Voltage / IAT-BCircuit Low Input",
  P1115:
    "Engine Coolant Temperature(ECT)Sensor Circuit Intermittent High Voltage / IAT-BCircuit High Input",
  P1116: "Engine Coolantsensoroutofrange / ECTSensor Out Of Self Test Range",
  P1117: "Engine Coolant Sensor intermittent / ECTSensor Intermittent",
  P1118: "Manifold Absolute Temperature Circuit Low Input",
  P1119: "Manifold Absolute Temperature Circuit High Input",
  P1120: "Throttlepositionsensoroutofrange",
  P1121: "Throttle Position(TP)Sensor Circuit Intermittent High Voltage",
  P1122: "Throttle Position(TP)Sensor Circuit Intermittent Low Voltage",
  P1123: "Throttle Position Sensor In Range But Higher Than Expected",
  P1124: "Throttle Position Sensor Out Of Self Test Range",
  P1125: "Throttlepositionsensor intermittent",
  P1126: "Throttle Position(Narrow Range)Sensor Circuit Malfunction",
  P1127: "Exhaust Not Warm,Downstream O2Sensor",
  P1128: "Upstream Heated O2Sensors Swapped",
  P1129: "Downstream Heated O2Sensors Swapped",
  P1130: "Lack Of HO2SSwitch-Adaptive Fuel At Limit",
  P1131: "Lack Of HO2SSwitch-Sensor Indicates Lean",
  P1132: "Lack Of HO2SSwitch-Sensor Indicates Rich",
  P1133: "HO2SInsufficient Switching Sensor1",
  P1134: "HO2STransition Time Ratio Sensor1",
  P1135: "Pedal Position Sensor ACircuit Intermittent",
  P1136: "Fan Control Circuit Malfunction",
  P1137: "Lack Of HO2SSwitch-Sensor Indicates Lean",
  P1138: "Lack Of HO2S12Switch-Sensor Indicates Rich",
  P1139: "Water In Fuel Indicator Circuit Malfunction",
  P1140: "Water In Fuel Condition",
  P1141: "Fuel Restriction Indicator Circuit Malfunction",
  P1142: "Fuel Restriction Condition",
  P1143: "Air Assist Control Valve Range / Performance",
  P1144: "Air Assist Control Valve Circuit Malfunction",
  P1150: "Lack Of HO2S21Switch-Adaptive Fuel At Limit",
  P1151: "Lack Of HO2S21Switch-Sensor Indicates Lean",
  P1152: "Lack Of HO2S21Switch-Sensor Indicates Rich",
  P1153: "Bank2Fuel Control Shifted Lean",
  P1154: "Bank2Fuel Control Shifted Rich",
  P1155: "Alternative Fuel Controller",
  P1156: "Fuel Select Switch Malfunction",
  P1157: "Lack Of HO2S22Switch-Sensor Indicates Lean",
  P1158: "Lack Of HO2S22Switch-Sensor Indicates Rich",
  P1159: "Fuel Stepper Motor Malfunction",
  P1167: "Invalid Test,throttlenotdepressed",
  P1168: "Fuel Rail Sensor In-Range Low Failure",
  P1169: "Fuel Rail Sensor In-Range High Failure",
  P1170: "ESO-Engine Shut Off Solenoid Fault",
  P1171: "Rotor Sensor Fault",
  P1172: "Rotor Control Fault",
  P1173: "Rotor Calibration Fault",
  P1174: "Cam Sensor Fault",
  P1175: "Cam Control Fault",
  P1176: "Cam Calibration Fault",
  P1177: "Synchronization Fault",
  P1178: "(open)",
  P1180: "Fuel Delivery System Malfunction-Low",
  P1181: "Fuel Delivery System Malfunction-High",
  P1182: "Fuel Shut Off Solenoid Malfunction",
  P1183: "Engine Oil Temperature Circuit Malfunction",
  P1184: "Engine Oil Temperature Out Of Self Test Range",
  P1185: "FTSHigh-Fuel Pump Temperature Sensor High",
  P1186: "FTSLow-Fuel Pump Temperature Sensor Low",
  P1187: "Variant Selection",
  P1188: "Calibration Memory Fault",
  P1189: "Pump Speed Signal Fault",
  P1190: "Calibration Resistor Out Of Range",
  P1191: "Key Line Voltage",
  P1192: "Voltage External",
  P1193: "EGRDrive Overcurrent",
  P1194: "ECUA / DConverter",
  P1195: "SCPHBCCFailed To Initialize",
  P1196: "Key Off Voltage High",
  P1197: "Key Off Voltage Low",
  P1198: "Pump Rotor Control Underfueling",
  P1199: "Fuel Level Input Circuit Low",
  P1200: "Injector Control Circuit",
  P1201: "Injector Circuit Open / Shorted-Cylinder#1",
  P1202: "Injector Circuit Open / Shorted-Cylinder#2",
  P1203: "Injector Circuit Open / Shorted-Cylinder#3",
  P1204: "Injector Circuit Open / Shorted-Cylinder#4",
  P1205: "Injector Circuit Open / Shorted-Cylinder#5",
  P1206: "Injector Circuit Open / Shorted-Cylinder#6",
  P1209: "Injector Control Pressure System Fault",
  P1210: "Injector Control Pressure Above Expected Level",
  P1211: "Injector Control Pressure Sensor Above / Below Desired",
  P1212: "Injector Control Pressure Not Detected During Crank",
  P1213: "Start Injector Circuit Malfunction",
  P1214: "Pedal Position Sensor BCircuit Intermittent",
  P1215: "Pedal Position Sensor CCircuit Low Input",
  P1216: "Pedal Position Sensor CCircuit High Input",
  P1217: "Pedal Position Sensor CCircuit Intermittent",
  P1218: "CIDHigh",
  P1219: "CIDLow",
  P1220: "Series Throttle Control System Malfunction",
  P1221: "Traction Control System Malfunction",
  P1222: "Traction Control Output Circuit Malfunction",
  P1223: "Pedal Demand Sensor BCircuit High Input",
  P1224: "Throttle Position Sensor BOut Of Self Test Range",
  P1225: "Needle Lift Sensor Malfunction",
  P1226: "Control Sleeve Sensor Malfunction",
  P1227: "Wastegate Failed Closed(Over Pressure)",
  P1228: "Wastegate Failed Open(Under Pressure)",
  P1229: "Intercooler Pump Driver Fault",
  P1230: "Fuel Pump Low Speed Malfunction",
  P1231: "Fuel Pump Secondary Circuit Low,High Speed",
  P1232: "Fuel Pump Speed Primary Circuit Malfunction",
  P1233: "Fuel Pump Driver Module Off Line",
  P1234: "Fuel Pump Driver Module Off Line",
  P1235: "Fuel Pump Control Out Of Range",
  P1236: "Fuel Pump Control Out Of Range",
  P1237: "Fuel Pump Secondary Circuit Malfunction",
  P1238: "Fuel Pump Secondary Circuit Malfunction",
  P1239: "Speed Fuel Pump Positive Feed Fault",
  P1240: "Sensor Power Supply Malfunction",
  P1241: "Sensor Power Supply Low Input",
  P1242: "Sensor Power Supply High Input",
  P1243: "Second Fuel Pump Faultyor Ground Fault",
  P1244: "Alternator Load Input Failed High",
  P1245: "Alternator Load Input Failed Low",
  P1246: "Alternator Load Input Failed",
  P1247: "Turbo Boost Pressure Low",
  P1248: "Turbo Boost Pressure Not Detected",
  P1249: "Wastegate Control Valve Performance",
  P1250: "PRCSolenoid Circuit Malfunction",
  P1251: "Air Mixture Solenoid Circuit Malfunction",
  P1252: "Pedal Correlation PDS1and LPDSHigh",
  P1253: "Pedal Correlation PDS1and LPDSLow",
  P1254: "Pedal Correlation PDS2and LPDSHigh",
  P1255: "Pedal Correlation PDS2and LPDSLow",
  P1256: "Pedal Correlation PDS1and HPDS",
  P1257: "Pedal Correlation PDS2and HPDS",
  P1258: "Pedal Correlation PDS1and PDS2",
  P1259: "Immobilizerto PCMSignal Error",
  P1260: "THEFTDetected,Vehicle Immobilzed",
  P1261: "Cylinder#1High To Low Side Short",
  P1262: "Cylinder#2High To Low Side Short",
  P1263: "Cylinder#3High To Low Side Short",
  P1264: "Cylinder#4High To Low Side Short",
  P1265: "Cylinder#5High To Low Side Short",
  P1266: "Cylinder#6High To Low Side Short",
  P1267: "Cylinder#7High To Low Side Short",
  P1268: "Cylinder#8High To Low Side Short",
  P1269: "Immobilizer Code Not Programmed",
  P1270: "Engine RPMOr Speed Limiter Reached",
  P1271: "Cylinder#1High To Low Side Open",
  P1272: "Cylinder#2High To Low Side Open",
  P1273: "Cylinder#3High To Low Side Open",
  P1274: "Cylinder#4High To Low Side Open",
  P1275: "Cylinder#5High To Low Side Open",
  P1276: "Cylinder#6High To Low Side Open",
  P1277: "Cylinder#7High To Low Side Open",
  P1278: "Cylinder#8High To Low Side Open",
  P1280: "Injection Control Pressure Out Of Range Low",
  P1281: "Injection Control Pressure Out Of Range High",
  P1282: "Excessive Injection Control Pressure",
  P1283: "IPRCircuit Failure",
  P1284: "Aborted KOER-ICPFailure",
  P1285: "Cylinderheadovertempsensed",
  P1286: "Fuel Pulse In Range But Lower Than Expected",
  P1287: "Fuel Pulse In Range But Higher Than Expected",
  P1288: "Cylinder Head Temp Sensor Out Of Self Test Range",
  P1289: "Cylinder Head Temp Sensor High Input",
  P1290: "Cylinder Head Temp Sensor Low Input",
  P1291: "Injector High Side Short To GNDOr VBATT-Bank1",
  P1292: "Injector High Side Short To GNDOr VBATT-Bank2",
  P1293: "Injector High Side Open-Bank1",
  P1294: "Injector High Side Open-Bank2 / Target idlenotreached",
  P1295: "Multi-faults-Bank1-With Low Side Shorts",
  P1296: "Multi-faults-Bank2-With Low Side Shorts",
  P1297: "Injector High Sides Shorted Together",
  P1298: "IDMFailure",
  P1299: "Cylinder Head Overtemperature Protection Active",
  P1300: "Boost Calibration Fault",
  P1301: "Boost Calibration High",
  P1302: "Boost Calibration Low",
  P1303: "EGRCalibration Fault",
  P1304: "EGRCalibration High",
  P1305: "EGRCalibration Low",
  P1306: "Kickdown Relay Pull-In Circuit Fault",
  P1307: "Kickdown Relay Hold Circuit Fault",
  P1308: "A / CClutch Circuit Fault",
  P1309: "Misfire Monitor AICEChip Fault",
  P1313: "Misfire Rate Catalyst Damage Fault-Bank1",
  P1314: "Misfire Rate Catalyst Damage Fault-Bank2",
  P1315: "Persistent Misfire",
  P1316: "Injector Circuit / IDMCodes Detected",
  P1317: "Injector Circuit / IDMCodes Not Updated",
  P1336: "Crank / Cam Sensor Range / Performance",
  P1340: "Camshaft Position Sensor BCircuit Malfunction",
  P1341: "Camshaft Position Sensor BRange / Performance",
  P1345:
    "SGC(Cam Position)Sensor Circuit Malfunction / Crankshaft Position-Camshaft Position Correlation",
  P1346: "Fuel Level Sensor BCircuit Malfunction",
  P1347: "Fuel Level Sensor BRange / Performance",
  P1348: "Fuel Level Sensor BCircuit Low",
  P1349: "Fuel Level Sensor BCircuit High",
  P1350: "Fuel Level Sensor BIntermittent / Bypass Line Monitor",
  P1351:
    "IDMInput Circuit Malfunction / Ignition Coil Control Circuit High Voltage",
  P1352: "Ignition Coil APrimary Circuit Malfunction",
  P1353: "Ignition Coil BPrimary Circuit Malfunction",
  P1354: "Ignition Coil CPrimary Circuit Malfunction",
  P1355: "Ignition Coil DPrimary Circuit Malfunction",
  P1360: "Ignition Coil ASecondary Circuit Malfunction",
  P1361: "Ignition Control (IC)Circuit Low Voltage",
  P1362: "Ignition Coil CSecondary Circuit Malfunction",
  P1363: "Ignition Coil DSecondary Circuit Malfunction",
  P1364: "Ignition Coil Primary Circuit Failure",
  P1365: "Ignition Coil Secondary Circuit Failure",
  P1366: "Ignition Spare",
  P1367: "Ignition Spare",
  P1368: "Ignition Spare",
  P1369: "Engine Temperature Light Monitor Failure",
  P1370: "Insufficient RMPIncrease During Spark Test",
  P1371: "Ignition Coil-Cylinder1-Early Activation Fault",
  P1372: "Ignition Coil-Cylinder2-Early Activation Fault",
  P1373: "Ignition Coil-Cylinder3-Early Activation Fault",
  P1374:
    "Crankshaft Position(CKP) / Ignition Coil-Cylinder4-Early Activation Fault",
  P1375: "Ignition Coil-Cylinder5-Early Activation Fault",
  P1376: "Ignition Coil-Cylinder6-Early Activation Fault",
  P1380: "Misfire Detected-Rough Road Data Not Available",
  P1381:
    "Variable Cam Timing Overadvanced(Bank#1) / Misfire Detected-No Communicationwith BCM",
  P1382: "Variable Cam Timing Solenoid#1Circuit Malfunction",
  P1383: "Variable Cam Timing Overretarded(Bank#1)",
  P1384: "VVTSolenoid AMalfunction",
  P1385: "Variable Cam Timing Solenoid BMalfunction",
  P1386: "Variable Cam Timing Overadvanced(Bank#2)",
  P1387: "Variable Cam Timing Solenoid#2Circuit Malfunction",
  P1388: "Variable Cam Timing Overretarded(Bank#2)",
  P1389: "Glow Plug Circuit High Side Low Input",
  P1390: "Octane Adjust Pin Out Of Self Test Range",
  P1391: "Glow Plug Circuit Low Input(Bank#1)",
  P1392: "Glow Plug Circuit High Input(Bank#1)",
  P1393: "Glow Plug Circuit Low Input(Bank#2)",
  P1394: "Glow Plug Circuit High Input(Bank#2)",
  P1395: "Glow Plug Monitor Fault(Bank#1)",
  P1396: "Glow Plug Monitor Fault(Bank#2)",
  P1397: "System Voltage Out Of Self Test Range",
  P1398: "VVTSolenoid BCircuit High Input",
  P1399: "Glow Plug Circuit High Side,High Input",
  P1400: "DPFECircuit Low Input",
  P1401: "DPFECircuit High Input",
  P1402: "EGRMetering Orifice Restricted",
  P1403: "DPFESensor Hoses Reversed",
  P1404:
    "IAT-BCircuit Malfunction / Exhaust Gas Recirculation Closed Position Performance",
  P1405: "DPFESensor Upstream Hose Off Or Plugged",
  P1406: "Exhaust Gas Recirculation(EGR)Position Sensor Performance",
  P1407: "EGRNo Flow Detected",
  P1408: "EGRFlow Out Of Self Test Range",
  P1409: "EVRControl Circuit Malfunction",
  P1411: "SAISystem Incorrect Downstream Flow Detected",
  P1413: "SAISystem Monitor Circuit Low Input",
  P1414: "SAISystem Monitor Circuit High Input",
  P1415: "Air Pump Circuit Malfunction / (AIR)System Bank1",
  P1416: "Port Air Circuit Malfunction / (AIR)System Bank2",
  P1417: "Port Air Relief Circuit Malfunction",
  P1418: "Split Air#1Circuit Malfunction",
  P1419: "Split Air#2Circuit Malfunction",
  P1420: "Catalyst Temperature Sensor Failure",
  P1421: "Catalyst Damage",
  P1422: "EGITemperature Sensor Failure",
  P1423: "EGIFunctionality Test Failed",
  P1424: "EGIGlow Plug Primary Failure",
  P1425: "EGIGlow Plug Secondary Failure",
  P1426: "EGIMini-MAFFailed Out Of Range",
  P1427: "EGIMini-MAFFailed Short Circuit",
  P1428: "EGIMini-MAFFailed Open Circuit",
  P1429: "Electric Air Pump Primary Failure",
  P1430: "Electric Air Pump Secondary Failure",
  P1433: "A / CRefrigerant Temperature Circuit Low",
  P1434: "A / CRefrigerant Temperature Circuit High",
  P1435: "A / CRefrigerant Temperature Circuit Range / Performance",
  P1436: "A / CEvaporator Air Temperature Circuit Low",
  P1437: "A / CEvaporator Air Temperature Circuit High",
  P1438: "A / CEvaporator Air Temperature Circuit Range / Performance",
  P1439: "Floor Temperature Switch Circuit Malfunction",
  P1440: "Purge Valve Stuck Open",
  P1441:
    "Evaporative Emission(EVAP)System Flow During Non-Purge Chevrolet Only",
  P1442: "Evaporative Emission Control System Leak Detected",
  P1443: "Evaporative Emission Control System Control Valve",
  P1444: "Purge Flow Sensor Circuit Low Input",
  P1445: "Purge Flow Sensor Circuit High Input",
  P1446: "Evaporative Vac Solenoid Circuit Malfunction",
  P1447: "ELCSystem Closure Valve Flow Fault",
  P1448: "ELCSystem2Fault",
  P1449: "Evaporative Check Solenoid Circuit Malfunction",
  P1450: "Unable To Bleed Up Fuel Tank Vacuum",
  P1451: "Evap Emission Control Sys Vent Control Valve Circuit",
  P1452: "Unable To Bleed-Up Vacuumin Tank",
  P1453: "Fuel Tank Pressure Relief Valve Malfunction",
  P1454: "Evaporative System Vacuum Test Malfunction",
  P1455: "Evap Emission Control Sys Leak Detected(Gross Leak / No Flow)",
  P1456: "Fuel Tank Temperature Sensor Circuit Malfunction",
  P1457: "Unable To Pull Vacuum In Tank",
  P1460: "Wideopenthrottle A / Ccutoffrelaycircuit",
  P1461: "A / Cpressuresensorcircuitvoltagelow",
  P1462: "A / Cpressuresensorcircuitvoltagehigh",
  P1463: "A / CPressure Sensor Insufficient Pressure Change",
  P1464: "A / CDemand Outof Self Test Range",
  P1465: "A / CRelay Circuit Malfunction",
  P1466: "A / CRefrigerant Temperature Sensor / Circuit Malfunction",
  P1467: "A / CCompressor Temperature Sensor Malfunction",
  P1468: "SSPODOpen Circuitor Closed Circuit Fault",
  P1469: "Low A / CCycling Period",
  P1470: "A / CCycling Period Too Short",
  P1471: "Electrodrive Fan1Operational Failure(Driver Side)",
  P1472: "Electrodrive Fan2Operational Failure(Passenger Side)",
  P1473: "Fan Secondary High With Fan(s)Off",
  P1474: "Low Fan Control Primary Circuit Malfunction",
  P1475: "Fan Relay(Low)Circuit Malfunction",
  P1476: "Fan Relay(High)Circuit Malfunction",
  P1477: "Additional Fan Relay Circuit Malfunction",
  P1478: "Cooling Fan Driver Fault",
  P1479: "High Fan Control Primary Circuit Malfunction",
  P1480: "Fan Secondary Lowwith Low Fan On",
  P1481: "Fan Secondary Low With High Fan On",
  P1482: "SCP",
  P1483: "Power To Fan Circuit Overcurrent",
  P1484: "Open Power To Ground VCRM",
  P1485: "EGRVCircuit Malfunction",
  P1486: "EGRACircuit Malfunction",
  P1487: "EGRCHKSolenoid Circuit Malfunction",
  P1490: "Secondary Air Relief Solenoid Circuit Malfunction",
  P1491: "Secondary Switch Solenoid Circuit Malfunction",
  P1492: "APLSOLSolenoid Circuit Malfunction",
  P1493: "RCNTSolenoid Circuit Malfunction",
  P1494: "SPCUTSolenoid Circuit Malfunction",
  P1495: "TCSPLSolenoid Circuit Malfunction",
  P1500: "Vehicle Speed Sensor Intermittent",
  P1501: "Vehicle Speed Sensor Out Of Self Test Range",
  P1502: "Vehicle Speed Sensor Intermittent Malfunction",
  P1503: "Auxillary Speed Sensor Fault",
  P1504: "Idle Air Control Circuit Malfunction",
  P1505: "Idle Air Control System At Adaptive Clip",
  P1506: "Idle Air Control Overspeed Error",
  P1507: "Idle Air Control Underspeed Error",
  P1508: "Idle Control System Circuit Open",
  P1509: "Idle Control System Circuit Shorted",
  P1510: "Idle Signal Circuit Malfunction",
  P1511: "Idle Switch(Electric Control Throttle)Circuit Malfunction",
  P1512: "Intake Manifold Runner Control (Bank1)Stuck Closed",
  P1513: "Intake Manifold Runner Control (Bank2)Stuck Closed",
  P1514: "High Load Neutral / Drive Fault",
  P1515: "Electric Current Circuit Malfunction",
  P1516: "IMRCInput Error(Bank1)",
  P1517: "IMRCInput Error(Bank2)",
  P1518: "Intake Manifold Runner Control (Stuck Open)",
  P1519: "Intake Manifold Runner Control (Stuck Closed)",
  P1520: "Intake Manifold Runner Control Circuit Malfunction",
  P1521: "Variable Intake Solenoid#1Circuit Malfunction",
  P1522: "Variable Intake Solenoid#2Circuit Malfunction",
  P1523: "IVCSolenoid Circuit Malfunction",
  P1524: "Variable Intake Solenoid System",
  P1525: "Air Bypass Valve System",
  P1526: "Air Bypass System",
  P1527: "Accelerate Warmup Solenoid Circuit Malfunction",
  P1528: "Subsidiary Throttle Valve Solenoid Circuit Malfunction",
  P1529: "SCAIRSolenoid Circuit Malfunction",
  P1530: "A / CClutch Circuit Malfunction",
  P1531: "Invalid Test-Accelerator Pedal Movement",
  P1532: "IMCCCircuit Malfunction,Bank B",
  P1533: "AAICircuit Malfunction",
  P1534: "Inertia Switch Activated",
  P1535: "Blower Fan Speed Circuit Range / Performance",
  P1536: "Parking Brake Switch Circuit Failure",
  P1537: "Intake Manifold Runner Control (Bank1)Stuck Open",
  P1538: "Intake Manifold Runner Control (Bank2)Stuck Open",
  P1539: "Power To A / CClutch Circuit Overcurrent",
  P1540: "Air Bypass Valve Circuit Malfunction",
  P1549: "IMCCCircuit Malfunction,Bank B",
  P1550: "PSPSOut Of Self Test Range",
  P1565: "Speed Control Command Switch Outof Range High",
  P1566: "Speed Control Command Switch Outof Range Low",
  P1567: "Speed Control Output Circuit Continuity",
  P1568: "Speed Control Unableto Hold Speed",
  P1571: "Brake Switch Malfunction",
  P1572: "Brake Pedal Switch Circuit Malfunction",
  P1573: "Throttle Position Not Available",
  P1574: "Throttle Position Sensor Disagreementbtwn Sensors",
  P1575: "Pedal Position Outof Self Test Range",
  P1576: "Pedal Position Not Available",
  P1577: "Pedal Position Sensor Disagreementbtwn Sensors",
  P1578: "ETCPower Less Than Demand",
  P1579: "ETCIn Power Limiting Mode",
  P1580: "Electronic Throttle Monitor PCMOverride",
  P1581: "Electronic Throttle Monitor Malfunction",
  P1582: "Electronic Throttle Monitor Data Available",
  P1583: "Electronic Throttle Monitor Cruise Disable",
  P1584: "TCUDetected IPECircuit Malfunction",
  P1585: "Throttle Control Unit Malfunction",
  P1586: "Throttle Control Unit Throttle Position Malfunction",
  P1587: "Throttle Control Unit Modulated Command Malfunction",
  P1588: "Throttle Control Unit Detected Lossof Return Spring",
  P1589: "TCUUnable To Control Desired Throttle Angle",
  P1600: "Lossof KAMPower;Open Circuit",
  P1601: "ECM / TCMSerial Communication Error",
  P1602: "Immobilizer / ECMCommunication Error",
  P1603: "EEPROMMalfunction",
  P1604: "Code Word Unregestered",
  P1605: "Keep Alive Memory Test Failure",
  P1606: "ECMControl Relay O / PCircuit Malfunction",
  P1607: "MILO / PCircuit Malfunction",
  P1608: "Internal ECMMalfunction",
  P1609: "Diagnostic Lamp Driver Fault",
  P1610: "SBDSInteractive Codes",
  P1611: "SBDSInteractive Codes",
  P1612: "SBDSInteractive Codes",
  P1613: "SBDSInteractive Codes",
  P1614: "SBDSInteractive Codes",
  P1615: "SBDSInteractive Codes",
  P1616: "SBDSInteractive Codes",
  P1617: "SBDSInteractive Codes",
  P1618: "SBDSInteractive Codes",
  P1619: "SBDSInteractive Codes",
  P1620: "SBDSInteractive Codes",
  P1621:
    "Control Module Long Term Memory Performance / Immobilizer Code Words Do Not Match",
  P1622: "Immobilizer IDDoes Not Match",
  P1623: "Immobilizer Code Word / IDNumber Write Failure",
  P1624: "Anti Theft System",
  P1625: "B+Supply To VCRMFan Circuit Malfunction",
  P1626:
    "Theft Deterrent Fuel Enable Signal Not Received / B+Supply To VCRMA / CCircuit Malfunction",
  P1627: "Module Supply Voltage Out Of Range",
  P1628: "Module Ignition Supply Input Malfunction",
  P1629: "Internal Voltage Regulator Malfunction",
  P1630: "Internal Vref Malfunction",
  P1631:
    "Theft Deterrent Start Enable Signal Not Correct / Main Relay Malfunction(Power Hold)",
  P1632: "Smart Alternator Faults Sensor / Circuit Malfunction",
  P1633: "KAMVoltage Too Low",
  P1634: "Data Output Link Circuit Failure",
  P1635: "Tire / Axle Ratio Outof Acceptable Range",
  P1636: "Inductive Signature Chip Communication Error",
  P1637: "Can Link ECM / ABSCMCircuit / Network Malfunction",
  P1638: "Can Link ECM / INSTMCircuit / Network Malfunction",
  P1639: "Vehicle IDBlock Corruptedor Not Programmed",
  P1640: "Powertrain DTCs Availablein Another Module",
  P1641: "Fuel Pump Primary Circuit Failure",
  P1642: "Fuel Pump Monitor Circuit High Input",
  P1643: "Fuel Pump Monitor Circuit Low Input",
  P1644: "Fuel Pump Speed Control Circuit Malfunction",
  P1645: "Fuel Pump Resistor Switch Circuit Malfunction",
  P1650: "PSPSwitch Outof Self Test Range",
  P1651: "PSPSwitch Input Malfunction",
  P1652: "IACMonitor Disabledby PSPSwitch Failed On",
  P1653: "Power Steering Output Circuit Malfunction",
  P1654: "Recirculation Override Circuit Malfunction",
  P1655: "Starter Disable Circuit Malfunction",
  P1660: "Output Circuit Check Signal High",
  P1661: "Output Circuit Check Signal Low",
  P1662: "IDM_ENCircuit Failure",
  P1663: "Fuel Demand Command Signal Circuit Malfunction",
  P1667: "CICircuit Malfunction",
  P1668: "PCM-IDMCommunications Error",
  P1670: "Electronic Feedback Signal Not Detected",
  P1680: "Metering Oil Pump Malfunction",
  P1681: "Metering Oil Pump Malfunction",
  P1682: "Metering Oil Pump Malfunction",
  P1683: "Metering Oil Pump Temperature Sensor Circuit Malfunction",
  P1684: "Metering Oil Pump Position Sensor Circuit Malfunction",
  P1685: "Metering Oil Pump Stepping Motor Circuit Malfunction",
  P1686: "Metering Oil Pump Stepping Motor Circuit Malfunction",
  P1687: "Metering Oil Pump Stepping Motor Circuit Malfunction",
  P1688: "Metering Oil Pump Stepping Motor Circuit Malfunction",
  P1689: "Oil Pressure Control Solenoid Circuit Malfunction",
  P1690: "Wastegate Solenoid Circuit Malfunction",
  P1691: "Turbo Pressure Control Solenoid Circuit Malfunction",
  P1692: "Turbo Control Solenoid Circuit Malfunction",
  P1693: "Turbo Charge Control Circuit Malfunction",
  P1694: "Turbo Charge Relief Circuit Malfunction",
  P1700: "Transmission Indeterminate Failure(Failedto Neutral)",
  P1701: "Reverse Engagement Error",
  P1702: "TRSCircuit Intermittent Malfunction",
  P1703: "Brake Switch Out Of Self Test Range",
  P1704: "Digital TRSFailedto Transition Statesin KOEO / KOER",
  P1705: "Not in Por NDuring KOEO / KOER",
  P1706: "High Vehicle Speed Observedin Park",
  P1707: "Transfer Case Neutral Indicator Hard Fault Present",
  P1708: "Clutch Switch Circuit Malfunction",
  P1709: "PNPSwitch Out Of Self Test Range",
  P1711: "TFTSensor Out Of Self Test Range",
  P1712: "Trans Torque Reduction Request Signal Malfunction",
  P1713: "TFTSensor In Range Failure Low Value",
  P1714: "SSAInductive Signature Malfunction",
  P1715: "SSBInductive Signature Malfunction",
  P1716: "SSCInductive Signature Malfunction",
  P1717: "SSDInductive Signature Malfunction",
  P1718: "TFTSensor In Range Failure High",
  P1720: "Vehicle Speed(Meter)Circuit Malfunction",
  P1721: "Gear1Incorrect Ratio",
  P1722: "Gear2Incorrect Ratio",
  P1723: "Gear3incorrect Ratio",
  P1724: "Gear4Incorrect Ratio",
  P1725: "Insufficient Engine Speed Increase During Self Test",
  P1726: "Insufficient Engine Speed Decrease During Self Test",
  P1727: "Coast Clutch Solenoid Inductive Signature Malfunction",
  P1728: "Transmission Slip Error",
  P1729: "4x4Low Switch Error",
  P1730: "Gear Control Malfunction2,3,5",
  P1731: "1-2Shift Malfunction",
  P1732: "2-3Shift Malfunction",
  P1733: "3-4Shift Malfunction",
  P1734: "Gear Control Malfunction",
  P1735: "First Gear Switch Circuit Malfunction",
  P1736: "Second Gear Switch Circuit Malfunction",
  P1737: "Lockup Solenoid System",
  P1738: "Shift Time Error",
  P1739: "Slip Solenoid System",
  P1740: "Torque Converter Clutch Inductive Signature Malfunction",
  P1741: "Torque Converter Clutch Control Error",
  P1742: "Torque Converter Clutch Solenoid Failed On",
  P1743: "Torque Converter Clutch Solenoid Failied On",
  P1744: "Torque Converter Clutch System Performance",
  P1745: "Line Pressure Solenoid System",
  P1746: 'Pressure Control Solenoid"A"Open Circuit',
  P1747: 'Pressure Control Solenoid"A"Short Circuit',
  P1748: "EPCMalfunction",
  P1749: "Pressure Control Solenoid Failed Low",
  P1751: "Shift Solenoid APerformance",
  P1754: "Coast Clutch Solenoid Circuit Malfunction",
  P1755: "Intermediate Speed Sensor(ISS)Malfunction",
  P1756: "Shift Solenoid BPerformance",
  P1760: 'Pressure Control Solenoid"A"Short Circuit',
  P1761: "Shift Solenoid CPerformance",
  P1762: "Overdrive Band Failed Off",
  P1765: "Timing Solenoid Circuit Malfunction",
  P1767: "Torque Converter Clutch Circuit Malfunction",
  P1768: "Performance / Normal / Winter Mode Input Malfunction",
  P1769: "AG4Transmission Torque Modulation Fault",
  P1770: "Clutch Solenoid Circuit Malfunction",
  P1775: "Transmission System MILFault",
  P1776: "Ignition Retard Request Duration Fault",
  P1777: "Ignition Retard Request Circuit Fault",
  P1778: "Transmission Reverse I / PCircuit Malfunction",
  P1779: "TCILCircuit Malfunction",
  P1780: "Trans Control Switch(O / DCancel)Outof Self Test Range",
  P1781: "4X4Switch Outof Self Test Range",
  P1782: "P / ESCircuit Out Of Self Test Range",
  P1783: "Transmission Overtemperature Condition",
  P1784: "Transmission Mechanical Failure-First And Reverse",
  P1785: "Transmission Mechanical Failure-First And Second",
  P1786: "3-2Downshift Error",
  P1787: "2-1Downshift Error",
  P1788: 'Pressure Control Solenoid"B"Open Circuit',
  P1789: 'Pressure Control Solenoid"B"Short Circuit',
  P1790: "TP(Mechanical)Circuit Malfunction",
  P1791: "TP(Electric)Circuit Malfunction",
  P1792: "Barometer Pressure Circuit Malfunction",
  P1793: "Intake Air Volume Circuit Malfunction",
  P1794: "Battery Voltage Circuit Malfunction",
  P1795: "Idle Switch Circuit Malfunction",
  P1796: "Kick Down Switch Circuit Malfunction",
  P1797: "Neutral Switch Circuit Malfunction",
  P1798: "Coolant Temperature Circuit Malfunction",
  P1799: "Hold Switch Circuit Malfunction",
  P1800: "Transmission Clutch Interlock Safety Switch Circuit Failure",
  P1801: "Transmission Clutch Interlock Safety Switch Open Circuit",
  P1802: "Transmission Clutch Interlock Safety Switch Short Circuit To Battery",
  P1803: "Transmission Clutch Interlock Safety Switch Short Circuit To Ground",
  P1804: "Transmission4-Wheel Drive High Indicator Circuit Failure",
  P1805: "Transmission4-Wheel Drive High Indicator Open Circuit",
  P1806: "Transmission4-Wheel Drive High Indicator Short Circuit To Battery",
  P1807: "Transmission4-Wheel Drive High Indicator Short Circuit To Ground",
  P1808: "Transmission4-Wheel Drive Low Indicator Circuit Failure",
  P1809: "Transmission4-Wheel Drive Low Indicator Open Circuit",
  P1810:
    "TFPValve Position Switch Circuit / Transmission4-Wheel Drive Low Indicator Short Circuit To Battery",
  P1811: "Transmission4-Wheel Drive Low Indicator Short Circuit To Ground",
  P1812: "Transmission4-Wheel Drive Mode Select Circuit Failure",
  P1813: "Transmission4-Wheel Drive Mode Select Open Circuit",
  P1814: "Transmission4-Wheel Drive Mode Select Short Circuit To Battery",
  P1815: "Transmission4-Wheel Drive Mode Select Short Circuit To Ground",
  P1816: "Transmission Neutral Safety Switch Circuit Failure",
  P1817: "Transmission Neutral Safety Switch Open Circuit",
  P1818: "Transmission Neutral Safety Switch Short Circuit To Battery",
  P1819: "Transmission Neutral Safety Switch Short Circuit To Ground",
  P1820:
    "Transmission Transfer Case Clockwise Shift Relay Coil Circuit Failure",
  P1821: "Transmission Transfer Case Clockwise Shift Relay Coil Open Circuit",
  P1822:
    "Transmission Transfer Case Clockwise Shift Relay Coil Short Circuit To Battery",
  P1823:
    "Transmission Transfer Case Clockwise Shift Relay Coil Short Circuit To Ground",
  P1824: "Transmission4-Wheel Drive Clutch Relay Circuit Failure",
  P1825: "Transmission4-Wheel Drive Clutch Relay Open Circuit",
  P1826: "Transmission4-Wheel Drive Low Clutch Relay Circuit To Battery",
  P1827: "Transmission4-Wheel Drive Low Clutch Relay Circuit To Ground",
  P1828:
    "Transmission Transfer Case Counter Clockwise Shift Relay Coil Circuit Failure",
  P1829:
    "Transmission Transfer Case Counter Clockwise Shift Relay Coil Open Circuit",
  P1830:
    "Transmission Transfer Case Counter Clockwise Shift Relay Coil Short Circuit To Battery",
  P1831:
    "Transmission Transfer Case Counter Clockwise Shift Relay Coil Short Circuit To Ground",
  P1832:
    "Transmission Transfer Case Differential Lock-Up Solenoid Circuit Failure",
  P1833:
    "Transmission Transfer Case Differential Lock-Up Solenoid Open Circuit",
  P1834:
    "Transmission Transfer Case Differential Lock-Up Solenoid Short Circuit To Battery",
  P1835:
    "Transmission Transfer Case Differential Lock-Up Solenoid Short Circuit To Ground",
  P1836: "Transmission Transfer Case Front Shaft Speed Sensor Circuit Failure",
  P1837: "Transmission Transfer Case Rear Shaft Speed Sensor Circuit Failure",
  P1838: "Transmission Transfer Case Shift Motor Circuit Failure",
  P1839: "Transmission Transfer Case Shift Motor Open Circuit",
  P1840: "Transmission Transfer Case Shift Motor Short Circuit To Battery",
  P1841: "Transmission Transfer Case Shift Motor Short Circuit To Ground",
  P1842:
    "Transmission Transfer Case Differential Lock-Up Feedback Switch Circuit Failure",
  P1843:
    "Transmission Transfer Case Differential Lock-Up Feedback Switch Open Circuit",
  P1844:
    "Transmission Transfer Case Differential Lock-Up Feedback Switch Short Circuit To Battery",
  P1845:
    "Transmission Transfer Case Differential Lock-Up Feedback Switch Short Circuit To Ground",
  P1846: "Transmission Transfer Case Contact Plate'A'Circuit Failure",
  P1847: "Transmission Transfer Case Contact Plate'A'Open Circuit",
  P1848: "Transmission Transfer Case Contact Plate'A'Short Circuit To Battery",
  P1849: "Transmission Transfer Case Contact Plate'A'Short Circuit To Ground",
  P1850: "Transmission Transfer Case Contact Plate'B'Circuit Failure",
  P1851: "Transmission Transfer Case Contact Plate'B'Open Circuit",
  P1852: "Transmission Transfer Case Contact Plate'B'Short Circuit To Battery",
  P1853: "Transmission Transfer Case Contact Plate'B'Short Circuit To Ground",
  P1854: "Transmission Transfer Case Contact Plate'C'Circuit Failure",
  P1855: "Transmission Transfer Case Contact Plate'C'Open Circuit",
  P1856: "Transmission Transfer Case Contact Plate'C'Short Circuit To Battery",
  P1857: "Transmission Transfer Case Contact Plate'C'Short Circuit To Ground",
  P1858: "Transmission Transfer Case Contact Plate'D'Circuit Failure",
  P1859: "Transmission Transfer Case Contact Plate'D'Open Circuit",
  P1860:
    "TCCPWMSolenoid Circuit Electrical / Transmission Transfer Case Contact Plate'D'Short Circuit To Battery",
  P1861: "Transmission Transfer Case Contact Plate'D'Short Circuit To Ground",
  P1862: "Transmission Transfer Case Contact Plate Power Circuit Failure",
  P1863: "Transmission Transfer Case Contact Plate Power Open Circuit",
  P1864: "Transmission Transfer Case Contact Plate Power Short To Battery",
  P1865: "Transmission Transfer Case Contact Plate Power Short To Ground",
  P1866: "Transmission Transfer Case System Concern-Servicing Required",
  P1867: "Transmission Transfer Case Contact Plate General Circuit Failure",
  P1868: "Transmission Automatic4-Wheel Drive Indicator(Lamp)Circuit Failure",
  P1869:
    "Transmission Automatic4-Wheel Drive Indicator(Lamp)Circuit Short To Battery",
  P1870:
    "Transmission Component Slipping / Transmission Mechanical Transfer Case4x4Switch Circuit Failure",
  P1871:
    "Transmission Mechanical Transfer Case4x4Switch Circuit Short To Battery",
  P1872: "Transmission Mechanical4-Wheel Drive Axle Lock Lamp Circuit Failure",
  P1873:
    "Transmission Mechanical4-Wheel Drive Axle Lock Lamp Circuit Short To Battery",
  P1874: "Transmission Automatic Hall Effect Sensor Power Circuit Failure",
  P1875:
    "Transmission Automatic Hall Effect Sensor Power Circuit Short To Battery / 4WDLow Switch Circuit Electrical",
  P1876: "Transmission Transfer Case2-Wheel Drive Solenoid Circuit Failure",
  P1877:
    "Transmission Transfer Case2-Wheel Drive Solenoid Circuit Short To Battery",
  P1878: "Transmission Transfer Case Disengaged Solenoid Circuit Failure",
  P1879: "Transmission Transfer Case Disengaged Solenoid Open Circuit",
  P1880: "Transmission Transfer Case Disengaged Solenoid Shortto Battery",
  P1881: "Engine Coolant Level Switch Circuit Failure,GEM",
  P1882: "Engine Coolant Level Switch Circuit Shortto Ground",
  P1883: "Engine Coolant Level Switch Circuit Failure,GEM",
  P1884: "Engine Coolant Level Lamp Circuit Shortto Ground",
  P1885: "Transmission Transfer Case Disengaged Solenoid Shortto Ground",
  P1886: "4X4Initialization Failure",
  P1890: "Transmission4WDMode Select Return Input Circuit Failure",
  P1891: "Transmission Transfer Case Contact Plate Ground Return Open Circuit",
  P1900: "OSSCircuit Intermittent Malfunction",
  P1901: "TSSCircuit Intermittent Malfunction",
  P1902: 'Pressure Control Solenoid"B"Intermittent Short',
  P1903: 'Pressure Control Solenoid"C"Short Circuit',
  P1904: 'Pressure Control Solenoid"C"Open Circuit',
  P1905: 'Pressure Control Solenoid"C"Intermittent Short',
  P1906: "Kickdown Pull Relay Openor Short Circuitto Ground",
  P1907: "Kickdown Hold Relay Openor Short Circuitto Ground",
  P1908: "Transmission Pressure Circuit Solenoid Openor Shortto Ground",
  P1909: "Trans Temp Sensor Circuit Openor Shortedto Pwror Gnd",
  P1910: "VFSAPressure Output Failed Low",
  P1911: "VFSBPressure Output Failed Low",
  P1912: "VFSCPressure Output Failed Low",
  P1913: "Pressure Switch ACircuit Malfunction",
  P1914: "Manually Shifted Automatic(MSA)Sw Circuit Malf",
  P1915: "Reverse Switch Circuit Malfunction",
  P1916: "High Clutch Drum Speed Sensor Malfunction",
  P1917: "High Clutch Drum Speed Sensor Intermittent",
  P1918: "Transmission Range Display Circuit Malfunction"
};

export function decodeDTC(code: string): string {
  return DTC_MAP[code] || "Unknown Diagnostic Trouble Code";
}
